export const teamMembers = [
    {
      name: "Samuel Habimana",
      title: "Founder & Executive Chairperson",
      imageUrl: "/sma.jpeg",
      description1: `A visionary leader with expertise in education, health care management, business, and global health delivery. He has extensive experience designing, implementing, and scaling health and youth empowerment initiatives.`,
      description2: `A passionate advocate for adolescent health, mentorship, and inclusive leadership, he works with schools, partners, and civil society to create lasting impact for young people.`,
    },
    {
      name: "Ms. Rachel Murekatete",
      title: "Founding Member",
      imageUrl: "/Rachel Murekatete, MSc.JPG",
      description1: `Public health professional with expertise in SRHR, gender equity, and youth empowerment. Supports program implementation and community engagement.`,
      description2: ``,
    },
    {
      name: "Dr. Dukundane Alexandre",
      title: "Founding Member",
      imageUrl: "/Dr. Alexandre Dukundane, MD, MSc.JPG",
      description1: `Clinician and health professional providing technical oversight for youth health programs and interventions. Passionate about improving access to reproductive and adolescent health services.`,
      description2: ``,
    },
    {
      name: "Dr. Mickline Kelly Mutoni",
      title: "Founding Member",
      imageUrl: "/Dr Kelly Mickline Mutoni, MD, MSc.JPG",
      description1: `Medical doctor with experience in clinical practice and global health initiatives. Provides guidance on SRHR and health program implementation.`,
      description2: ``,
    },
    {
      name: "Mr. Muhire Gustave",
      title: "Founding Member",
      imageUrl: "/Gustave Muhire, MSc.JPG",
      description1: `Global health advocate specializing in gender, SRHR, and marginalized communities. Leads initiatives promoting inclusive health policies and youth empowerment.`,
      description2: ``,
    },
      {
        name: "Aime Emmanuel Musabyimana",
        title: "Founding Member",
        imageUrl: "/Aime Emmanuel Musabyimana.png",
        description1: `Communications lead managing advocacy, public engagement, and strategic campaigns to ensure HAYi's programs reach youth effectively.`,
        description2: ``,
      },
      {
        name: "Dr. Christelle Giraneza Uwantege",
        title: "Founding Member",
        imageUrl: "/Dr. Christelle Uwantege Giraneza, MD, MSc.JPG",
        description1: `Clinician and SRHR advocate, also CMO of URUKUNDO Initiative. Supports health education, youth mentorship, and program outreach.`,
        description2: ``,
      },
      {
        name: "Dr. Simeon Turatsinze",
        title: "Founding Member",
        imageUrl: "/Dr. Simeon Turatsinze, MD, MSc.JPG",
        description1: `Medical doctor and global health professional with expertise in maternal health, research, and health system strengthening. Contributes to evidence-based interventions and mentorship.`,
        description2: ``,
      },
      {
        name: "Odette Nishimwe",
        title: "Founding Member",
        imageUrl: "/Odette Nishimwe, MSc.JPG",
        description1: `Global health professional and researcher focused on innovation, scalable health solutions, and improving operational and communication processes.`,
        description2: ``,
      },
      {
        name: "Wellars Mvuyekure",
        title: "Founding Member",
        imageUrl: "/Mvuyekure.jpg",
        description1: `Public health and Gender/SRHR specialist focused on advancing health equity, project management, and community-driven interventions.`,
        description2: ``,
      },
      {
        name: "Dr. Florence Dusabimana",
        title: "Founding Member",
        imageUrl: "/Dr Florence Dusabimana.jpeg",
        description1: `Midwife with expertise in maternal and neonatal health. Leads training programs and supports interventions to reduce maternal and neonatal mortality.`,
        description2: ``,
      },
      {
        name: "Yves Ndayambaje",
        title: "Founding Member",
        imageUrl: "/Yves Ndayambaje.png",
        description1: `Professional in academic support, project management, and partnerships, driving efficiency, sustainability, and equitable outcomes.`,
        description2: ``,
      },
      {
        name: "Janviere Iradukunda",
        title: "Founding Member",
        imageUrl: "/Janviere Iradukunda.jpeg",
        description1: `Procurement and logistics specialist expanding expertise in communication management, supporting organizational operations and impact-driven strategies.`,
        description2: ``,
      },
  ];  